import { NextResponse } from 'next/server';

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { symbol, currentPrice, alertType, message, discordWebhookUrl } = body;

    if (!discordWebhookUrl) {
      return NextResponse.json({ error: 'Missing Discord Webhook URL' }, { status: 400 });
    }

    // สร้าง Rich Embed Box ส่งไปยัง Discord ให้ดูเป็นมืออาชีพ
    const discordPayload = {
      username: "Gemini Financial Analyst",
      avatar_url: "https://ai.google.dev/static/images/favicon.png", 
      embeds: [
        {
          title: `🚀 [${alertType}] Signal Alert for ${symbol}`,
          description: message,
          color: alertType === 'BUY' ? 5763719 : 16001053, // สีเขียว หรือ สีแดง
          fields: [
            {
              name: "Current Price",
              value: `$${currentPrice.toFixed(2)}`,
              inline: true
            },
            {
              name: "Analysis Type",
              value: "Technical & AI Convergence",
              inline: true
            }
          ],
          footer: {
            text: "Generated by Financial Analysis App • Gemini 3.5 Flash Engine",
          },
          timestamp: new Date().toISOString()
        }
      ]
    };

    const response = await fetch(discordWebhookUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(discordPayload),
    });

    if (!response.ok) {
      throw new Error('Failed to dispatch message to Discord');
    }

    return NextResponse.json({ success: true, message: 'Notification sent successfully' });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
